routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Model\Photo;
use App\Model\TodoItem;
use Illuminate\Support\Facades\Input;
use Symfony\Component\HttpFoundation\Request;

Route::get('/', function () {
    return redirect('todo/index');
});

Route::group(['prefix' => 'todo', 'as' => 'todo.'], function () {
    Route::get('index', function () {

        $todos = TodoItem::all();
        return view('todo/index')->with('items', $todos);
    })->name('index');
    Route::post('add', function (Request $request) {

        $item = new TodoItem();
        $item->name = $request->get('title');
        $item->save();
        return redirect('todo/index');
    })->name('add');
    Route::get('toogle/{id}', function ($id) {

        $item = TodoItem::all()->find($id);
        $item->finished = !$item->finished;
        $item->save();
        return redirect('todo/index');
    })->name('toogle');
    Route::get('delete/{id}', function ($id) {

        $item = TodoItem::all()->find($id);
        $item->delete();
        return redirect('todo/index');
    })->name('delete');
});

Route::group(['prefix' => 'gallerie', 'as' => 'gallerie.'], function () {
    Route::get('index', function () {
        $photoa = Photo::all();
        return view('gallerie/index')->with('items',$photoa);
    })->name('index');
    Route::post('add', function (Request $request) {
        $photo = new Photo();
        $photo->description = $request->get('desc');
        $image = Input::file('file');
        $path = $image->store('public/image/');
        //dump($path);
        $photo->path = Storage::url($path);
        $photo->save();
        return redirect('gallerie/index');
    })->name('add');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use App\Model\Photo;
use Illuminate\Http\Request;

class PhotoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function show(Photo $photo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function edit(Photo $photo)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Photo $photo)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Photo  $photo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Photo $photo)
    {
        //
    }
}

app/Http/Controllers/TodoItemController.php
<?php

namespace App\Http\Controllers;

use App\Model\TodoItem;
use Illuminate\Http\Request;

class TodoItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\TodoItem  $todoItem
     * @return \Illuminate\Http\Response
     */
    public function show(TodoItem $todoItem)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\TodoItem  $todoItem
     * @return \Illuminate\Http\Response
     */
    public function edit(TodoItem $todoItem)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\TodoItem  $todoItem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TodoItem $todoItem)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\TodoItem  $todoItem
     * @return \Illuminate\Http\Response
     */
    public function destroy(TodoItem $todoItem)
    {
        //
    }
}

resources/views/gallerie/index.blade.php
@extends('welcome')

@section('content')

    <div class="card mt-5">
        <div class="card-title">
            Gallerie
        </div>
        <div class="card-body">
            <form action="{{route('gallerie.add')}}" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <div class="row">
                    <div class="col-9">
                        <input class="form-control" name="file" type="file" required placeholder="Tache a faire">
                        <input class="form-control mt-3" name="desc" type="text" required placeholder="Description">
                    </div>
                    <div class="col-3">
                        <button type="submit" class="btn btn-secondary mt-4">Ajouter une photo</button>
                    </div>
                </div>

            </form>
            <div class="border-success">

                <div class="row mt-2">
                    <div class="col-12">
                        <div id="nanogallery2"

                             data-nanogallery2='{
                            "thumbnailHeight":  150,
                            "thumbnailWidth":   150,
                            "itemsBaseURL":     ""
                            }'>
                            @foreach($items as $photos)
                                <a href="{{asset($photos->path)}}"
                                   data-ngThumb="{{asset($photos->path)}}"> {{$photos->description}} </a>
                            @endforeach
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@stop

resources/views/todo/index.blade.php
@extends('welcome')

@section('content')

    <div class="card mt-5">
        <div class="card-title">
            Les Todos
        </div>
        <div class="card-body">
            <form action="{{route('todo.add')}}" method="post">
                {{csrf_field()}}
                <div class="row">
                    <div class="col-11">
                        <input class="form-control" name="title" type="text" required placeholder="Tache a faire">
                    </div>
                    <div class="col-1">
                        <button type="submit" class="btn btn-secondary">+</button>
                    </div>
                </div>

            </form>
            <div class="border-success">
                @foreach($items as $todo)
                    <div class="row mt-2">
                        <div class="col-2"><a href="{{route('todo.toogle',['id'=>$todo->id])}}"
                                              class="btn @if($todo->finished) btn-warning @else btn-success @endif">
                                @if($todo->finished)
                                    non terminer @else terminer @endif</a></div>
                        <div class="col-9"><span>{{$todo->name}} </span></div>
                            <div class="col-1"><a href="{{route('todo.delete',['id'=>$todo->id])}}" class="btn btn-danger"> Effacer </a></div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>

@stop